//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelatorioDiscador
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfg_campaign
    {
        public decimal dbid { get; set; }
        public Nullable<decimal> tenant_dbid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<decimal> script_dbid { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<decimal> csid { get; set; }
        public Nullable<decimal> tenant_csid { get; set; }
        public Nullable<decimal> script_csid { get; set; }
    }
}
